all: snake
	./snake casos/testes/simples/1/mapa.txt < casos/testes/simples/1/movimentos.txt


snake:
	gcc -o snake snake.c

clean:
	rm -rf inicializacao.txt resumo.txt heat_map.txt estatisticas.txt ranking.txt snake
